name: mustang_cli
description: mustang_cli for Mustang.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
