name: mustang_core
description: A starting point for Dart libraries or applications.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build_resolvers: ^2.0.4
  flutter:
    sdk: flutter
  hive: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
