name: mustang_core
description: >
  A framework to build Flutter applications. It provides state management, persistence, caching and
  opinionated project structure.

version: 1.1.0
repository: https://github.com/getwrench/open_mustang

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_resolvers: ^2.0.4
  hive: ^2.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.2

