name: mustang_core
description: >
  A framework to build Flutter applications. It provides state management, persistence, caching and
  opinionated project structure.

version: 3.3.0
repository: https://github.com/getwrench/open_mustang

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_resolvers: ^2.2.0
  hive: ^2.0.4
  built_collection: ^5.1.1
  built_value: ^8.6.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
