name: mustang_core
description: State management, core widgets and utils for Mustang.
version: 1.0.0
homepage: https://github.com/getwrench/open_mustang
repository: https://github.com/getwrench/open_mustang/mustang_core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_resolvers: ^2.0.4
  flutter:
    sdk: flutter
  hive: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
