name: mustang_core
description: >
  A framework to build Flutter applications. Following features are available out of the box.

  - State Management
  - Persistence
  - Cache
  - File layout and naming standards
  - Reduces boilerplate with `open_mustang_cli` (https://pub.dev/packages/open_mustang_cli)

version: 1.0.1
repository: https://github.com/getwrench/open_mustang/mustang_core.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_resolvers: ^2.0.4
  flutter:
    sdk: flutter
  hive: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
