name: mustang_core
description: >
  A framework to build Flutter applications. It provides state management, persistence, caching and
  opinionated project structure.

version: 1.1.12
repository: https://github.com/getwrench/open_mustang

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  build_resolvers: ^2.0.4
  hive: ^2.0.4
  built_collection: ^5.1.1
  built_value: ^8.1.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
