name: mustang_widgets
description: >
  Flutter widgets to use while building application using Mustang framework. This package should be added as a dev dependency.

version: 3.0.0
repository: https://github.com/getwrench/open_mustang

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
