name: core
description: Mustang - Framework to build applications in Flutter
version: 1.0.0
homepage: https://bitbucket.org/lunchclub/mustang/src

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
