builders:
  #  mustang_config_builder:
  #    import: 'package:mustang_codegen/builder.dart'
  #    builder_factories: [ 'mustangConfigBuilder' ]
  #    build_extensions: { '.yaml': [ '.dart' ] }
  #    auto_apply: root_package
  #    build_to: source
  #    runs_before: [ 'mustang_codegen:model_builder' ]
  model_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'appModelLibraryBuilder' ]
    build_extensions: { '.dart': [ '.model.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        exclude: [ '**/models/*.model.dart', '**/models/*.model.g.dart' ],
        include: [ '**/models/*.dart' ]
      }
    }
  batch_run_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'appBatchLibraryBuilder' ]
    build_extensions: { '.dart': [ '.batch.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        exclude: [ '**/batches/*.batch.dart' ],
        include: [ '**/batches/*.dart' ]
      }
    }
  app_serializer_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'appSerializerBuilder' ]
    build_extensions: { '.dart': [ '.ser.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
  aspect_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'appAspectLibraryBuilder' ]
    build_extensions: { '.dart': [ '.aspect.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        exclude: [ '**/aspects/*.aspect.dart' ],
        include: [ '**/aspects/*.dart' ]
      }
    }
  state_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'screenStateLibraryBuilder' ]
    build_extensions: { '.dart': [ '.state.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        include: [ '**/screens/**/*_state.dart' ]
      }
    }
  screen_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'screenLibraryBuilder' ]
    build_extensions: { '.dart': [ '.screen.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        include: [ '**/screens/**/*_screen.dart' ]
      }
    }
  service_builder:
    import: 'package:mustang_codegen/builder.dart'
    builder_factories: [ 'screenServiceLibraryBuilder' ]
    build_extensions: { '.dart': [ '.service.dart' ] }
    auto_apply: root_package
    build_to: source
    runs_before: [ 'mustang_codegen:built_value' ]
    defaults: {
      generate_for: {
        include: [ '**/screens/**/*_service.dart' ]
      }
    }
  # https://github.com/google/built_value.dart/blob/master/built_value_generator/build.yaml
  built_value:
    target: ':built_value_generator'
    import: 'package:built_value_generator/builder.dart'
    builder_factories: [ 'builtValue' ]
    build_extensions: { '.dart': [ '.built_value.g.part' ] }
    auto_apply: root_package
    build_to: cache
    applies_builders: [ 'source_gen|combining_builder' ]
    defaults: {
      generate_for: {
        include: [ '**/models/*.model.dart',
                   '**/models/serializers.dart' ]
      }
    }
