name: mustang_codegen
description: Codegen for Mustang.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_value_generator: ^8.0.6
  glob: ^2.0.1
  meta: ^1.3.0
  mustang_core:
    git:
      url: git@bitbucket.org:lunchclub/mustang.git
      path: mustang_core
      ref: 07-jun-21
  path: ^1.8.0
  source_gen: ^1.0.0
  analyzer: ^1.7.1
  build: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4

#dependency_overrides:
#  mustang_core:
#    path: ../mustang_core
