name: mustang_codegen
description: Codegen for Mustang.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  built_value_generator: ^8.0.6
  glob: ^2.0.1
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0
  mustang_core:
    git:
      url: git@bitbucket.org:lunchclub/mustang.git
      path: mustang_core
      ref: master

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
