name: mustang_codegen
description: Codegen for Mustang.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  built_value_generator: ^8.1.3
  glob: ^2.0.2
  mustang_core:
    git:
      url: git@bitbucket.org:lunchclub/open_mustang.git
      path: mustang_core
      ref: master
  path: ^1.8.0
  source_gen: ^1.1.1

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.19.2
