name: mustang_codegen
description: Codegen for Mustang.
version: 1.0.0
homepage: https://github.com/getwrench/open_mustang
repository: https://github.com/getwrench/open_mustang/mustang_codegen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  glob: ^2.0.2
  mustang_core: ^1.0.0
  path: ^1.8.0
  source_gen: ^1.1.1

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.19.2
